name = "Base Scenario"
description = "A simple economy with two banks, one oil refinery, and a few consumers."

[config]
iterations = 100
treasury_tenors_to_register = ["T2Y", "T5Y", "T10Y", "T30Y"]

[[banks]]
id = "bank_a"
name = "Ravelin National Bank"
initial_reserves = 5000000.0
initial_bonds = [
    { tenor = "T10Y", face_value = 500000.0 }
]

[[banks]]
id = "bank_b"
name = "Economic Sim Savings & Loan"
initial_reserves = 3000000.0
initial_bonds = [
    { tenor = "T2Y", face_value = 200000.0 },
    { tenor = "T10Y", face_value = 150000.0 }
]

[[firms]]
id = "global_oil"
name = "Global Oil Corp"
bank_id = "bank_a"
recipe_name = "Oil Refining"
initial_cash = 250000.0
initial_inventory = [
    { good_slug = "oil", quantity = 1000.0, unit_cost = 50.0 }
]

[[consumers]]
id = "consumer_1"
bank_id = "bank_a"
initial_cash = 5000.0
income = 60000.0 # Annual

[[consumers]]
id = "consumer_2"
bank_id = "bank_b"
initial_cash = 7500.0
income = 85000.0 # Annual