[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
sim_core = { workspace = true }
domains = { workspace = true }
engine_v3 = { workspace = true }

uuid = { workspace = true }
chrono = { workspace = true }
dyn-clone = "1.0.20"
rand = { workspace = true }

axum = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tower-http = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["fmt"] }