[package]
name = "playground"
version = "0.1.0"
edition = "2024"

[dependencies]
sim_core = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["fmt"] }
tracing = "0.1.41"
chrono = { workspace = true }
uuid = { workspace = true }
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }