[package]
name = "ravelin_macros"
version = "0.1.0"
edition = "2024" # Or "2024"

[lib]
proc-macro = true # This is essential

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0.95"
