[[goods]]
slug = "oil"
name = "Crude Oil"
unit = "barrel"
category = "RawMaterial"
cpi_weight = 0.0

[[goods]]
slug = "petrol"
name = "Petrol"
unit = "gallon"
category = "Energy"
cpi_weight = 0.3

[[recipes]]
name = "Oil Refining"
output = { slug = "petrol", qty = 19.5 }
inputs = [
  { slug = "oil",   qty = 1.0 }
]
labourHours = 0.5
capitalRequired = 100.0
efficiency = 0.85