[package]
name = "engine_v3"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
sim_core = { workspace = true }
domains = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
rand = { workspace = true }
parking_lot = { workspace = true }
inventory = "0.3.21"
petgraph.workspace = true
uuid = { workspace = true }
toml.workspace = true
axum.workspace = true
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }
serde_with = { workspace = true }
tracing = "0.1.41"
