[package]
name = "ravelin_traits"
version = "0.1.0"
edition = "2024"

[lib]
name = "ravelin_traits"
path = "src/lib.rs"

[dependencies]
dyn-clone = "1.0.20"
rand = "0.9.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
