[package]
name = "sim_effects"
version = "0.1.0"
edition = "2024"

[dependencies]
sim_types = { path = "../sim_types" }
serde = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
